### ISSUE TITLE
US28 - Iniciar uma fiscalização

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#116]
Eu, como conselheiro, desejo iniciar uma fiscalização através de um agendamento, para que os dados da fiscalização sejam vinculados corretamente ao agendamento previamente efetuado.

**Tasks:**
- [x] Ao clicar em fiscalizar, deve-se abrir uma tela com três sub-telas (Exemplo do Wpp com as telas de:  Status - Chats - Calls);
- [x] As sub-telas serão: Pendentes - Fiscalizados - Expirados;
- [x] Todos os agendamentos devem aparecer com os dados: Nome da Escola, Data, Hora e se tem agente convidado ou não;
- [x] Deve ter um botão "Fiscalizar" que deve levar para a página de relatórios para a fiscalização;
- [x] O botão "Fiscalizar" deve ser clicável se o conselheiro for **convidado** para participar, se ele **estiver confirmado**;
- [x] Todas essas condições devem ser informadas através de **labels** no agendamento para o conselheiro;
  - **Caso o conselheiro não seja convidado** deve aparecer uma label no agendamento: "Você não foi convidado" (Label na cor que preferir);
  - **Caso o conselheiro não tenha confirmado** deve aparecer uma label no agendamento: "Você não confirmou o agendamento" (Label na cor que preferir);
- [ ] Testar;
