### ISSUE TITLE
TS23 - Bloquear alterações no relatório

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#121]
Eu, como desenvolvedor, desejo bloquear alterações no relatório após concluído para manter os dados inseridos seguros alterações indevidas.

**Tasks:**
- [ ] Criar um "Alert" para informar o conselheiro que a ação é irreversível e que ele pode acessar outros relatórios sem concluir o que está aberto - apenas retornando com o botão de voltar do celular;
- [ ] Não deixar o relatório clicável novamente caso seja concluído e mostrar uma tag de concluído na frente;
- [ ] Remover o check que aparece na frente do relatório caso ele tivesse marcado todo o relatório, isso foi substituído pela conclusão do relatório que será implementado nessa história.
