### ISSUE TITLE
Discutir funcionalidades restantes com o Cliente

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#153]
### Descrição
Deve-se marcar uma reunião com a Cliente para discutir as funcionalidades restantes para uma nova release.

### Tasks
Assuntos a tratar (issues devem ser criadas para tratar isso posteriormente):
- [ ] Fiscalização fora do Agendamento (just-in-time);
- [ ] Realizar deploy para IOS;
- [ ] Mostrar todas as escolas do munícipio (Limitação da Nuvem e quantidade de Dados);
- [ ] Layout da aplicação;
- [ ] Autenticação para permitir que somente presidentes reais se cadastrem na aplicação;
