### ISSUE TITLE
Modificar estrutura de navegação

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#158]
### Descrição
Modificar a estrutura de navegação para utilizar as propriedades da __Scene__ oferecidas pelo __Router Flux__.

### Tasks
- [ ] Remover todos os backs de todas as telas.
- [ ] Colocar o back diretamente no arquivo Routes.js.
- [ ] Verificar a possibilidade de remoção do componente __Header__ e a utilização do componente __navBar__ que o __Router Flux__ oferece.
- [ ] Se possível, realizar a troca acima.
