### ISSUE TITLE
Campo genérico de Input

### ISSUE THREAD

**Issue by SabinoGs** [fga-gpp-mds/2017.2-MerendaMais#173]
### Descrição
Eu como desenvolvedor desejo que exista um componente genérico de input para evitar o número de componentes no projeto.

### Tasks
 - [x] Criar arquivo GenericField.js
 - [x] Permitir a mudança do `título` através de `props`
 - [x] Permitir a mudança do `placeholder` através de `props`
 - [x] Permitir a definição de `regra validadora`, ou Regex, através de `props`
 - [x] Definir a mensagem de erro através de `props` 
 - [x] Definir o ícone, se houve a necessidade de uso, através de `props` 

### Justificativa adicional

InputFields, como os da tela de cadastro, podem ser substituídos por esse módulo genérico, facilitando a evolução e manutenção do código.
