### ISSUE TITLE
US20 - Consultar Cartilha

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#19]
Eu, como conselheiro, desejo consultar informações da cartilha para saber detalhes relacionados ao procedimento de fiscalização.

**Tasks:**
- [ ] Criar um botão na SideBar que leve a consulta da Cartilha;
- [ ] Deve-se abrir uma tela com as seções maiores das cartilhas em formato de botões em um lista;
- [ ] Ao pressionar o botão da seção deve-se abrir a seção da Cartilha correspondente a ela;
- [ ] A seção da cartilha deve ser acessada localmente, e deve abrir na própria aplicação ou utilizando um software de terceiros para abrir PDFs;
- [ ] Estudar soluções para realização de pesquisas por String no PDF.

**Comment by Rdlenke** [comment]
Inicialmente, a ideia da história era implementar uma tela com diversos botões ou seções. Quando esses botões fossem pressionados, o PDF da cartilha abriria na seção desejada.

Encontramos diversos pacotes para gerenciar o controle dos PDFs utilizando <i>React Native</i>,
 como <a href="https://github.com/wonday/react-native-pdf">React-Native-PDF</a>, <a href ="https://github.com/cnjon/react-native-pdf-view">React-Native-PDF-View</a>, e até pacotes que transferem para o sistema operacional a responsabilidade de gerenciar a abertura do PDF, como o <a href="https://github.com/huangzuizui/react-native-file-opener">React-Native-File-Opener</a> e o <a href="https://github.com/philipphecht/react-native-doc-viewer">React-Native-Doc-Viewer</a>. Porém, todos esses pacotes utilizam a linguagem nativa dos dispositivos  (Java e Objective-C) para fazer o gerenciamento.

Como o Merenda Mais foi construido utilizando o __Expo__, ele é um __Expo App__, o que significa que todo o código implementado deve ser escrito em javascript. Isso faz com que não seja possível utilizar essas bibliotecas.

Sem uma forma de gerenciar a abertura de PDFs no aplicativo, a forma de se realizar a história seria transcrever o conteúdo da cartilha para telas do aplicativo, utilizando um design que permita que o conselheiro a use da melhor forma possível. 

Como o time não possui habilidades de design para fazer essa implementação da maneira correta e desejada pelo cliente, essa história não foi realizada.

**Comment by Rdlenke** [comment]
Essa issue foi resolvida de acordo com as sugestões da @RochaCarla e será integrada ao aplicativo na issue #18.

O acesso à cartilha será feito através de um link para download na tela de acesso a legislação.
