### ISSUE TITLE
US21 - Consultar Reunião

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#20]
Eu, como conselheiro, desejo consultar uma reunião marcada para saber suas informações.

**Tasks:**
- [x] Ao clicar no botão da sideBar "Notificações" será aberta uma tela com dois botões, a tela criada nessa história deverá ser aberta ao clicar no botão "Convites de Reuniões", que será criado na História #95 ;
- [x] Deve-se seguir o modelo da tela de Notificações referentes a Visitas feita na História #95;
- [x] Só devem aparecer as notificações na tela correspondentes a reuniões que ainda estão pra acontecer;
   - Exemplo: Hoje é dia 12/04/17. Reuniões para até o dia 11/04/17 devem aparecer, depois disso, não aparecem mais.
- [x] Deve ser possível abrir a localização da reunião no maps, assim como acontece nas informações da escola;
- [x] Deve-se ter um botão (+ Informações) para cada reunião para acessar as informações completas da reunião e os convidados para esta reunião em questão;
- [x] Testar;
