### ISSUE TITLE
US19 - Agendar Reunião

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#22]
Eu, como conselheiro, desejo agendar uma reunião para realizar decisões acerca do CAE.

**Tasks:**
- [x] Criar botão na sideBar;
- [x] Deve seguir a mesma estrutura do Agendamento de Visita;
- [x] Em vez de escolher uma escola, deve-se escolher uma localização no Maps e armazenar a latitude longitude do local, ou o link referente ao acesso do local (Tomar de exemplo o link que abre o maps no schoolInformation);
   - Caso nada dê certo ao pegar a localização, pode ser um campos de texto para informação em linguagem natural do endereço da Reunião;
- [x] Deve-se poder convidar somente os conselheiros do CAE do próprio conselheiro;
- [x] Deve-se criar um campo opcional de Descrição da Reunião;
- [x] As opções serão: Escolher localização, Data, Hora, Convidar conselheiros, Descrição da Reunião.
- [x] A reunião só pode ser marcada caso os campos Escolher localização, Data, Hora e Convidar conselheiros estejam preenchidos;
- [x] Testar;

**Comment by AllanNobre** [comment]
Esta US é originária da Sprint 6 e se tornou uma dívida técnica por não ter sido concluída. Ela foi replanejada para a Sprint 7 para ser concluída nela.
