### ISSUE TITLE
US23 - Convidar Conselheiro

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#23]
Eu, como conselheiro, desejo convidar outro(s) conselheiro(s) para realizarem à visita à escola comigo.

**Tasks:**
- [x] Deve-se abrir um Pop-Up com uma lista dos conselheiros do CAE do autor do agendamento (Caso o POP-Up fique muito complexo, verificar com o ProductOwner a criação de uma tela);
- [x] Cada conselheiro deve aparecer na lista de uma forma default e quando for selecionado de alguma forma pelo autor do agendamento, deve ficar marcado;
- [x] Quando todos os conselheiros convidados forem marcados na lista, o conselheiro - autor do agendamento - terá a opção de cancelar ou confirmar;
- [x] Após os conselheiros serem convidados, eles devem aparecer como uma lista na tela de Agendamento, para indicar quais foram escolhidos (Usar mesma estrutura de aparição dos dados da escola);
- [x] Ao enviar a postagem para ser salva com os dados dos convidados, deve-se armazenar o ID deles com uma variável booleana que indicará se o conselheiro convidado confirmou ou não a presença.

**Comment by LucasAmoedo** [comment]
Oh, eu estava nessa Issue :o
