### ISSUE TITLE
US05 - Preencher Checklist de Estoque de Alimentos

### ISSUE THREAD

**Issue by Rdlenke** [fga-gpp-mds/2017.2-MerendaMais#52]
Eu, como conselheiro, desejo preencher a checklist de estoque de alimentos para que os relatórios da fiscalização possam ser gerados posteriormente.

**_Tasks_**:

- [x] Criar tela da checklist;
- [x] Criar cada pergunta da checklist e suas possívels opções (sim e não);
- [x] Escolher melhor forma de armazenar a resposta na store;
- [x] Indicar quantas telas/perguntas faltam para finalizar aquela checklist.
- [x] Criar campo opcional de informações extras para a checklist.
