### ISSUE TITLE
US14 - Desativar conselheiros da aplicação

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#73]
Eu, como presidente, desejo desativar conselheiros da aplicação para remover os conselheiros que não devem mais estar associados ao software.

**Tasks:**
- [x] Ao clicar no botão de desvincular Conselheiro, o perfil da nossa aplicação deve ser desassociado da conta da Nuvem do conselheiro, e ele deve desaparecer da lista de conselheiros do CAE;
- [x] Deve aparecer uma mensagem de confirmação na tela: "Você deseja realmente desassociar esse Conselheiro da Aplicação?";
- [x] * Ao clicar em Sim deve aparecer uma confirmação na tela caso o conselheiro seja desassociado com sucesso;
- [x] * Caso dê algum erro ao desassociar o conselheiro, o usuário também deve ser informado;
- [x] Para realizar essas ações, será usado o **token** do usuário dono da aplicação na Nuvem, logo deve ser autenticado no código para que o **token** seja obtido. Contudo, os dados de e-mail e senha do usuário dono da aplicação na Nuvem não podem estar armazenados diretamente no código, pois todos terão acesso, e isso é perigoso, logo deve-se fazer de uma forma que esses dados sejam protegidos de acessos indevidos;
- [x] O conselheiro deve ser removido do Grupo do CAE na Nuvem;
- [x] Testar.

OBS: * essas tasks devem seguir o modelo de feedback utilizado na #45.

**Comment by AllanNobre** [comment]
É importante para essa história verificar se a funcionalidade que permite a um usuário desassociar outro usuário na Nuvem Cívica com um token geral da aplicação será implementada pelos desenvolvedores da Nuvem Cívica.

**Comment by SkiaBr23** [comment]
@AllanNobre, invadindo o repositório de vocês aqui pra mandar um feedback sobre isso =D

Sobre a funcionalidade de desassociar o usuário da Nuvem, acredito que uma alternativa mais segura (para os casos de usuários que utilizam outros serviços da nuvem) seja a gerência por meio dos perfis. Ou seja, o presidente teria a permissão pra desassociar o perfil de "conselheiro" de certo usuário. 

Encontrei uma falha nas operações de perfil e aplicativo no que tange a autenticação, e estou corrigindo no momento. Quando ficar pronto, as permissões de associação/desassociação/alteração de perfil serão restritas ao usuário em questão OU à credencial do responsável pelo aplicativo ---> Dessa forma, rola de implementar do lado do cliente uma lógica de que um usuário com _role_ de Presidente faça uma autenticação com as credenciais de responsável ("token geral da aplicação") e tenha poder sobre todas as operações sob os usuários conselheiros. 

Se ficou confuso (provavelmente), podemos conversar mais sobre esse ponto. Sugiro criar uma _issue_ lá no repositório da nuvem e eu vou comunicando por lá.

[]'s

**Comment by AllanNobre** [comment]
@SkiaBr23, Beleza, eu entendi. Logo mais eu abro a issue no repositório da Nuvem sobre isso, obrigado pelo feedback.

**Comment by SkiaBr23** [comment]
@AllanNobre, respondi a [issue](https://github.com/AppCivicoPlataforma/AppCivico/issues/90), e a funcionalidade já está implementada.

**Comment by AllanNobre** [comment]
@SkiaBr23 , muito obrigado e perdão pela demora no feedback! A funcionalidade foi testada e está funcionando perfeitamente, qualquer dúvida nós daremos o feedback, bom trabalho, mito.
