### ISSUE TITLE
US11 - Realizar o log out na aplicação

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#76]
Eu, como conselheiro, desejo realizar o log out na aplicação, para poder encerrar minha sessão com segurança.

**Task:**
- [x] Deve-se criar um botão na sideBar para realização do LogOut;
- [x] Ao entrar na aplicação através do Login ou do Cadastro, o usuário não deve ser capaz de retornar para as telas de Login, Cadastro e Tela Inicial que possui os botões de Login e Cadastro, podendo acessar essas telas somente realizando o LogOut da aplicação;
- [x] Deve-se tomar cuidado em especial, pois no IOS não existe o botão de retornar a tela anterior, contudo tem-se o **slide para a esquerda** que volta a tela anterior. Teste em Android e IOS para verificar se funciona pros dois;
- [x] Deve-se implementar a função de voltar a tela anterior no botão de **voltar** do Header;
- [x] Ao apertar o botão de LogOut o usuário deve voltar para a tela Inicial que possui os botões de Login e Cadastro;
- [x] Testar;
