### ISSUE TITLE
TS13 - Aprimorar o layout da sideBar

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#77]
Eu, como desenvolvedor, desejo aprimorar o layout da sideBar, para prover ao conselheiro uma navegação mais intuitiva e agradável.

**Tasks:**
- [x] Verificar como utilizar os ícones do **React Native Elements** já instalado na aplicação;
  - https://oblador.github.io/react-native-vector-icons/
- [x] Trocar todos os ícones da aplicação para os ícones do **React Native Elements**;
- [x] Aplicar layout na sideBar similar ao protótipo, utilizando os ícones ideais do **React Native Elements**, criando contornos cada opção clicável como se fossem "botões" da sideBar;
