### ISSUE TITLE
US15 - Marcar os conselheiros como checados ou não checados

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#85]
Eu, como presidente, desejo marcar os conselheiros como checados ou não checados para ter ciência de quais conselheiros já foram verificados como reais conselheiros.

**Tasks:**
- [x] Utilizar um atributo do perfil do conselheiro na Nuvem Cívica para indicar se ele já foi checado ou não pelo Presidente.
- [x] Mostrar de forma sugestiva na tela que o presidente acessa todos os conselheiros do CAE quais estão validados ou não.
- [x] Ao clicar em validar um conselheiro, deve-se mudar a linha do conselheiro na tela para indicar que foi validado e o botão de validar deve mudar para invalidar.
- [ ] Testar.

**Comment by LucasAmoedo** [comment]
B-)
