### ISSUE TITLE
US13 - Ver o botão de agendar visita caso a escola seja do meu município ou UF

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#90]
Eu, como conselheiro, desejo somente ver o botão de agendar visita caso a escola seja do meu município ou UF, para não cometer um erro e agendar uma visita em uma escola fora do meu domínio.

**Tasks:**
- [x] Deve-se checar o tipo de CAE do Conselheiro e o CAE no momento em que este clicar para ver os dados de uma escola.
- [x] Se for Estadual, o botão de agendar visita deve aparecer se a UF da escola for a mesma do CAE do conselheiro.
- [x] Se for Municipal, o botão de agendar visita deve aparecer se o Município e a UF da escola for o mesmo do CAE do conselheiro.
- [x] Os campos de pesquisa UF e Município devem ser dropDowns, iguais ao da tela de registro;
- [x] Os dois campos dropdown devem aparecer sempre na tela, contudo o dropdown de municípios, irá mudar de acordo com a UF escolhida no dropdown de UFs;
