### ISSUE TITLE
US12 - Encerrar uma fiscalização

### ISSUE THREAD

**Issue by AllanNobre** [fga-gpp-mds/2017.2-MerendaMais#91]
Eu, como conselheiro, desejo encerrar uma fiscalização, para que os dados sejam armazenados com sucesso e possam ser acessados posteriormente.

**Tasks:**
- [x] Deve ter um botão "Participantes" no agendamento apresentado na tela que mostrará um Pop-Up com os conselheiros que irão participar com os dados: nome do conselheiro, se está confirmado ou não e se realizou a fiscalização ou não;
- [x] Deve-se criar um botão para realizar a finalização da fiscalização na tela de fiscalizar.
- [ ] Ao confirmar a finalização da fiscalização, os dados devem ser salvos na Nuvem da forma correta, utilizando o sistema de postagens.
- [ ] Deve-se realizar todas as conexões necessárias - armazenar na nuvem com o nuvemCode da postagem do agendamento associado - para que a fiscalização encerrada esteja corretamente associada com o agendamento e com os relatórios de dados de dados marcados.
- [ ] Deve-se modificar o Agendamento salvo na Nuvem para que a variável que indica se o conselheiro fiscalizou ou não esse agendamento seja true, após a fiscalização ser salva na Nuvem com sucesso. 
- [x] Arrumar layout da tela de relatórios para que a "MainReport" fique mais agradável.
- [ ] Testar.
